### ISSUE TITLE
gain.js example script - only 1st switch light works

### ISSUE THREAD

**Issue by SteveRussell33** [VCVRack/VCV-Prototype#14]
![proto1](https://user-images.githubusercontent.com/41975381/65783555-f3292b80-e147-11e9-8398-5bc5e14106d2.png)
![proto2](https://user-images.githubusercontent.com/41975381/65783574-f91f0c80-e147-11e9-9a28-92ab23c0fc6e.png)

**Comment by AndrewBelt** [comment]
Thanks, fixed in 7304094
