### ISSUE TITLE
Using other .js libraries?

### ISSUE THREAD

**Issue by michaelpalumbo** [VCVRack/VCV-Prototype#16]
First up, THANK YOU for making this module. I'm thrilled and have a few ideas already. 

If I wanted to include an extended js Lib, like Math.js for example, will the prototype still work?

**Comment by AndrewBelt** [comment]
Related issue https://github.com/VCVRack/VCV-Prototype/issues/15

**Comment by michaelpalumbo** [comment]
@AndrewBelt thanks

**Comment by AndrewBelt** [comment]
I'm going to close this as a duplicate.
