### ISSUE TITLE
watching changes to code saved in a different directory

### ISSUE THREAD

**Issue by michaelpalumbo** [VCVRack/VCV-Prototype#18]
I love that the prototype module reloads the script (I'm currently working in javascript) whenever I save it. However, I found a limitation where it won't remember the path if I load a .js file from a folder *other* than the plugins folder. This means that:

1. The watcher isn't catching when filechanges are made
2. If I click to open a new file, the open dialog starts within the /plugins/prototype/examples folder, rather than the same directory as the file I previously loaded)

I can work without **2**, but **1** is pretty key, since I'm collaborating on modules with others within git repositoriess. I assume this requires storing the absolute path, but I don't know cpp very well atm.

**Comment by AndrewBelt** [comment]
You should limit one bug per issue so I'll address the main one.

What is an example of a full path that is not being watched? In addition to that information, what is the path reported in the patch file under the JSON `.data.path`?

**Comment by michaelpalumbo** [comment]
Huh, strange it works now. Maybe I had to reopen rack after creating a new file path? If I can reproduce the error I'll reopen the issue.
