### ISSUE TITLE
unique circumstance where .js file will not re-instantiate when saved

### ISSUE THREAD

**Issue by michaelpalumbo** [VCVRack/VCV-Prototype#22]
Hi there. I created a .js script for prototype, verified it would reinstantiate in rack whenever i saved changed to the js script. I built a patch around it, saved the .vcv file in the same folder as the .js script. Then I zipped that folder and sent it to a friend. He was able to run the patch, but when he made changes to the .js code and saved it, it did not reinstantiate in vcv rack. I was able to reproduce this myself as well.

**Comment by AndrewBelt** [comment]
This is expected behavior. Patches refer to scripts with absolute paths, using the embedded script string as a fallback. Your friend is using the fallback. He needs to load the script in VCV Prototype by navigating to the new location if he wants to make changes to it.

**Comment by michaelpalumbo** [comment]
ah ok. thanks for this, i'll make sure notify him.
