### ISSUE TITLE
VCO.JS LINE 19 PART OF CODE IN COMMENT STATEMENT

### ISSUE THREAD

**Issue by alvingoesdown** [VCVRack/VCV-Prototype#23]
Hello was looking over the vco.js  code and noticed line 19 has some code in the comment at the end of the URL.  The code reads 
#pitch-and-frequencies 
Was this intended to be a comment, or is it code?
Thank you

**Comment by JerrySievert** [comment]
https://github.com/VCVRack/VCV-Prototype/blob/master/examples/vco.js#L19

it appears to be a URL fragment, specifically a link to https://vcvrack.com/manual/VoltageStandards.html#pitch-and-frequencies

and is part of a comment, as per the `//` part of the line.

**Comment by AndrewBelt** [comment]
@JerrySievert is right.
