### ISSUE TITLE
Feature request: make text labels writable

### ISSUE THREAD

**Issue by instrumaniak** [VCVRack/VCV-Prototype#30]
Hello, I am experimenting with VCV-Prototype by writing basic scripts and I love this ability to write javascript to prototype basic ideas in VCVRack. The UI is generic enough for prototyping a lot of things but I would love to have the ability to also change the text of the labels, so that for example after loading a script I would have better idea of what the knobs and switches are for by just looking at the UI first. For example: Instead of guessing what "K1" knob does it would be nice to see it's label say "Gain".

So I request to have the ability to set all the labels of VCV-Prototype from script, just like a script writer can change the color of leds. It would be understandable to have character limitations as long text labels wouldn't fit the UI.

Really thanks for creating VCV-Prototype!

**Comment by AndrewBelt** [comment]
The font of labels on VCV Prototype is Gotham Rounded, which is proprietary, so it cannot be redistributed.
