### ISSUE TITLE
Clean up Pure Data strings regarding "VCV"

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/VCV-Prototype#37]
"VCV" is the company, "Rack" is the flagship product. However, this project is "VCV Prototype".
Some strings used in `template.pd`, etc are imprecise. Are "fromVCV" and "toVCV" to be treated as IDs or human-readable strings? If IDs, maybe something like "fromPrototype" would be better. If human strings, maybe "from VCV Prototype".
"VCVRack" is sloppy and doesn't contain a space. "audio to VCVRack" should be changed to "audio to VCV Prototype".

**Comment by mxa** [comment]
IMO from the perspective of the Pd patch, `toRack`, `toVCVRack` or to a lesser extend `toVCVPrototype` would make more sense. `ToPrototype` is a bit weird because at that moment the Pd patch _is_ the prototype, or at least a part of it.

**Comment by AndrewBelt** [comment]
Are "fromVCV" etc IDs or just human-readable strings? What about removing references of VCV Rack/Prototype out of the PD patch? Is there a generic "audio out"/"audio in" terminology in Pure Data? Is it possible to make a patch in normal Pure Data and convert it to a VCV Prototype patch with minimal changes?

**Comment by mxa** [comment]
Since the audio is simply `[adc~ 1 2 3 4 5 6]` and `[dac~ 1 2 3 4 5 6]`, maybe the messages should be a generic` [receive input]` and `[print output]` then.

**Comment by AndrewBelt** [comment]
I say leave them out if they're not IDs.

**Comment by mxa** [comment]
They need to have an explicit name since the backend filters the messages for these strings.

**Comment by AndrewBelt** [comment]
Okay then, are you sure that `receive input` and `print output` are the *best* terms you can come up with? Remember that once your scripting API is released, it cannot be changed. In 10 years I don't want to have any regrets or complaining users because the API is "weird", so it needs to be done right the first time.

**Comment by mxa** [comment]
The only downside of generic terms would be that there is a chance users use these variables already.
How about

`[receive fromRack]` _receiving data from VCV Prototype module_
`[print toRack]` _sending data to VCV Prototype module_

**Comment by AndrewBelt** [comment]
What about `input/output`? What the default in Pure Data?

**Comment by mxa** [comment]
There is no default in _Pure Data_ for this as _Pure Data_ doesn't know about a host. _libpd_ is the only place where this concept is known and there isn't a default either. 
Pro generic `input/output`: It is as generic as `adc/dac`
Contra: variables should be precise and descriptive, generic variables may already be used in user patches.

**Comment by AndrewBelt** [comment]
Alright, that's fine. Just wanted to make sure you've put some thought into every API detail, since it can't be changed after release. If you think everything in the API is fine, could you declare it finalized on this issue thread? I'll make a release shortly after that.

**Comment by mxa** [comment]
Implemented with https://github.com/VCVRack/VCV-Prototype/commit/a131b2db186395ab03c599c16f068a67a628c349
