### ISSUE TITLE
Explain Windows libpd build flags

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/VCV-Prototype#40]
https://github.com/VCVRack/VCV-Prototype/blob/ec3f417651aa885bf4dedf952cfb149a5a26829f/Makefile#L224-L232
Could you explain these flags with a comment above each one, or if any are not needed, remove them.
I've commented out the ones that don't seem to be required when running a libpd script.
In particular I'm curious about `_WIN32` since mingw GCC already defines this on Windows, `-shared` since Rack plugins are already built with this flag, and `-static-libgcc` because statically linking the libgcc library since this library is already loaded dynamically into the global symbol table (via Rack).

**Comment by clwe** [comment]
Hi Andrew! 

I checked on my windows machine and confirmed that the additional flags are in deed not needed. So I removed them. 

I'm not sure where pure data uses the Winsock library. I guess for OSC and other networking? The PD_INTERNAL leaves the function declarations for libpd unchanged as opposed to not specifying it, which would enable the  "EXTERN __declspec(dllexport) extern" macro which then throughs a linker error. I guess this macro should only be used for the windows specific .dll dynamic linking format. The corresponding #define resides in "m_pd.h" inside pure data sources. 

I'm surprised that it builds without the -lkernel32 flag, though. I was using dependecy walker to see what was missing on windows intitially and saw related function stubs showing up. Maybe it's imported somewhere else already.
The other build flags came from the original libpd makefile. I guess we don't need them then!

All the best, Clemens
