### ISSUE TITLE
LGPL scripting engines?

### ISSUE THREAD

**Issue by rorywalsh** [VCVRack/VCV-Prototype#48]
I have Csound support working, but I don't think I can statically link to it as it uses the LGPL. Does anyone know if this is correct? It would be nice to include it, but not if it involves packaging additional runtime libraries.

**Comment by AndrewBelt** [comment]
VCV Prototype is GPLv3.0+, Csound is LGPLv2.1+. The LGPLv3.0 license allows Csound to be included in Prototype in any form: dynamic/static linking, copy-pasting code, making a derivative work of it, etc.
