### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by mossheim** [VCVRack/VCV-Prototype#50]
Since v1.3.0, it looks like both the faust and SC engines are newly available. A new tag should be pushed to indicate this milestone.

**Comment by AndrewBelt** [comment]
Prototype 1.4.0 hasn't been released yet, hence no tag.

**Comment by mossheim** [comment]
@AndrewBelt what features are necessary for 1.4.0? all I'm asking is that a new release should be made sometime soon to reflect major new functionality.
