### ISSUE TITLE
Make compile more modular [feature request]

### ISSUE THREAD

**Issue by mxa** [VCVRack/VCV-Prototype#53]
Now that the Prototype module supports so many languages, compiling has become quite a long process. It's unpractical for testing to delete the `dep` folder and compile everything again.
How about skipping a module if the subfolder in `deb` already exists? So for example if i'm working on the libpd plugin i just delete this subfolder and when running `make dep` it will assume that the plugins where the folders already exist were successfully build and it will just build the libpd plugin?

**Comment by AndrewBelt** [comment]
I think the build system is already pretty modular. For example if `FAUST` is set to 1, the Makefile checks if `dep/lib/libfaust.a` exists. If not, it builds it. If you want to disable it, set `FAUST` to 0. If you want to rebuild Faust, remove `dep/lib/libfaust.a` and perhaps `dep/faust` to start from scratch.

**Comment by mxa** [comment]
OK, I think I've overlooked these options in the makefile itself.
