### ISSUE TITLE
QuickJS exclusive build

### ISSUE THREAD

**Issue by jpnielsen** [VCVRack/VCV-Prototype#63]
Managed to build VCV-Prototype 2.3.0 [f693e76](https://github.com/VCVRack/VCV-Prototype/commit/f693e763335b5912ddfc2f8e26f687ffcf3693e6) on Windows 11 Msys64

Edited Makefile to a QUICKJS only build

```
DUKTAPE ?= 0
QUICKJS ?= 1
LUAJIT ?= 0
PYTHON ?= 0
SUPERCOLLIDER ?= 0
VULT ?= 0
LIBPD ?= 0
FAUST ?= 0
```

patched with the changes  ( did it manually - I don't know how to merge PR in my local git clone)

https://github.com/VCVRack/VCV-Prototype/pull/58/commits/0dac1aa65b7b02795a533d31200af54d6c6bec9d
https://github.com/VCVRack/VCV-Prototype/pull/62/commits/7a3d948d9c95a70382f5ddebecf635647c3f6c8b

`make` gave errors:

```
src/Prototype.cpp: In member function 'void Prototype::editScript()':
src/Prototype.cpp:507:49: error: 'toWstring' is not a member of 'rack::string'
  507 |                 std::wstring commandW = string::toWstring(command);
      |                                                 ^~~~~~~~~
make: *** [../../compile.mk:72: build/src/Prototype.cpp.o] Error 1
```
changed a line `src/Prototype.cpp`.
It's my novice guess as to what replaced string::toWstring - Only tested basic functionality on  Windows 11 English.

[line 507:  `std::wstring commandW = string::toWstring(command);`](https://github.com/VCVRack/VCV-Prototype/blob/f693e763335b5912ddfc2f8e26f687ffcf3693e6/src/Prototype.cpp#L507)
changed to:  `std::wstring commandW = rack::string::UTF8toUTF16(command);`

<img width="187" alt="image" src="https://user-images.githubusercontent.com/27916597/153558325-7fbb3c16-6824-46e9-8154-4de5bfe0a6b6.png">

**Comment by squinkylabs** [comment]
probably this is the new version:
std::wstring UTF8toUTF16(const std::string& s);

only available for windows (look in string.hpp)

Oh, I read farther, that's exactly what you did. But you will cause problems with non windows builds if you aren't careful.

**Comment by modlfo** [comment]
The suggested change is already in place. Thanks!
