### ISSUE TITLE
building with libpd support

### ISSUE THREAD

**Issue by porres** [VCVRack/VCV-Prototype#66]
Seems there are simple fixes/adjustments to be made so Prototype can be compiled with libpd support for VCV 2.0.

@clwe please let us know here when you get to this. I also hope you could help trying to compile this with some Pd externals (like ELSE/Cyclone).

**Comment by dizzisound** [comment]
Hi, just a quick report about my test-build.
I managed to build VCV-Prototype enabling QuickJS, LuaJit and libPD under Windows 10.
A summary of my main steps and edits:
- cloned the VCV-Prototype repo
- checked out the `v2` branch
- fixed the line 507 in `Prototype.cpp`:
https://github.com/VCVRack/VCV-Prototype/blob/739c0f5e90f3df8d7910b32fc0f58935f212d17d/src/Prototype.cpp#L507
with this line:
`std::wstring commandW = string::UTF8toUTF16(command); `
this fix was also suggested in this issue: 
https://github.com/VCVRack/VCV-Prototype/issues/63
but no pull-request followed the issue
- run the following command: 
`pacman -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang`
- did the following in the VCV-Prototype `Makefile`
1. enabled the LIBPD flag, i.e. `LIBPD ?= 1`
2. in the # LibPD section of the `Makefile`, added the line: `FLAGS += -DPDINSTANCE -DPDTHREADS`
3. in the `$(libpd):` target of the `Makefile`, changed the referenced commit to point at _libpd 0.13.2_:
	`cd dep/libpd && git checkout e3980d2fe45ef9eaaec1d45e4d68637eaf76a8b1`
	
I hope I didn't forget anything.
I dropped the installable plugin on my Google drive:
https://drive.google.com/drive/folders/1aW9TDz8VCEzb1VRvPtBPfqVH2Y76w09m?usp=sharing

**Comment by clwe** [comment]
I have been looking briefly into the libpd build yesterday. For Linux all that is needed is a different submodule checkout for libpd as suggested by @dizzisound. Thanks for finding that. The mentioned build flags are there already. I would need to look into windows and Mac builds soon.

**Comment by SteveRussell33** [comment]
>     * fixed the line 507 in `Prototype.cpp`:

https://github.com/VCVRack/VCV-Prototype/blob/739c0f5e90f3df8d7910b32fc0f58935f212d17d/src/Prototype.cpp#L507

>       
>       with this line:
>       `std::wstring commandW = string::UTF8toUTF16(command); `
>       this fix was also suggested in this issue:
>       [QuickJS exclusive build #63](https://github.com/VCVRack/VCV-Prototype/issues/63)
>       but no pull-request followed the issue
Fixed here 96d6305e89af82a39fb96578d2d25ac5d10f9ed1

**Comment by clwe** [comment]
This issue is fixed in [v2-tmp branch](/VCVRack/VCV-Prototype/tree/v2-tmp) and can be closed now. Superfluous build flags can be removed again via the pull request https://github.com/VCVRack/VCV-Prototype/pull/75
